---
Name: selfassessment
After: 'rhino#extensions'
---

SelfAssessment:
  extensions:
    - SelfAssessmentExtension
  allowed_field_types:
    - SelfAssessmentQuestion

SelfAssessmentReport:
  extensions:
    - SelfAssessmentReportExtension
